import streamlit as st
import py3Dmol
import os

# =============================
# 1️⃣ Streamlit Setup
# =============================
st.set_page_config(page_title="Protonic: Protein Structure Viewer", layout="wide")
st.title("🧬 Protonic: Realistic Protein 3D Visualization")

st.markdown("""
### Overview
This interactive interface visualizes **predicted protein structures** generated by the Protonic model.
Select a protein, rotate and zoom in the 3D viewer, and provide usability feedback.
""")

# =============================
# 2️⃣ Protein Demo Options
# =============================
demo_sequences = {
    "Protein 1 — demo1": "pdbs/demo1.pdb",
    "Protein 2 — demo2": "pdbs/demo2.pdb",
    "Protein 3 — demo3": "pdbs/demo3.pdb"
}

seq_name = st.selectbox("🧫 Select a protein structure:", list(demo_sequences.keys()))
pdb_file = demo_sequences[seq_name]

# =============================
# 3️⃣ Display 3D Protein Structure
# =============================
if st.button("🔮 Show 3D Structure"):
    if not os.path.exists(pdb_file):
        st.error("PDB file not found.")
    else:
        with open(pdb_file, "r") as f:
            pdb_data = f.read()

        view = py3Dmol.view(width=800, height=500)
        view.addModel(pdb_data, "pdb")
        view.setStyle({'cartoon': {'color': 'spectrum'}})
        view.zoomTo()
        st.components.v1.html(view._make_html(), height=500)
        st.success("✅ Realistic protein structure loaded successfully!")

# =============================
# 4️⃣ HCI FEEDBACK SECTION
# =============================
st.markdown("---")
st.header("🧠 User Feedback")

col1, col2 = st.columns(2)
usability = col1.slider("Ease of Use (1–5)", 1, 5, 4)
visual_quality = col2.slider("3D Visualization Quality (1–5)", 1, 5, 4)
comments = st.text_area("Comments or Suggestions:")

if st.button("💾 Submit Feedback"):
    st.success("✅ Thank you for your feedback! It has been recorded.")
